---
# tasks file for raveshaww.updates
- name: Run apt updates
  ansible.builtin.apt:
    name: "*"
    state: "latest"
    update_cache: true
    cache_valid_time: 3600

- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: true
