---
# handlers file for raveshaww.updates
- name: Remove unused APT packages
  ansible.builtin.apt:
    autoremove: true
  when: ansible_distribution_file_variety == "Debian"

- name: Remove unused DNF packages
  ansible.builtin.dnf:
    autoremove: true
  when: ansible_distribution_file_variety == "RedHat"
