---
name: Ansible Galaxy
"on":
  workflow_call:

defaults:
  run:
    working-directory: "raveshaww.updates"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: "raveshaww.updates"

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger Ansible Galaxy import
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
