---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  molecule:
    uses: ./.github/workflows/molecule.yml
    needs: [lint]
